### ISSUE TITLE
Angular injection error

### ISSUE THREAD

**Issue by timcullen** [danialfarid/angular-file-upload#498]
I get the following error on page load:

Error: [$injector:unpr] http://errors.angularjs.org/1.2.23/$injector/unpr?p0=%24uploadProvider%20%3C-%20%24upload
    at Error (native)
    at http://localhost:9000/bower_components/angular/angular.min.js:6:450
    at http://localhost:9000/bower_components/angular/angular.min.js:36:202
    at Object.c [as get] (http://localhost:9000/bower_components/angular/angular.min.js:34:305)
    at http://localhost:9000/bower_components/angular/angular.min.js:36:270
    at c (http://localhost:9000/bower_components/angular/angular.min.js:34:305)
    at d (http://localhost:9000/bower_components/angular/angular.min.js:35:6)
    at Object.instantiate (http://localhost:9000/bower_components/angular/angular.min.js:35:165)
    at http://localhost:9000/bower_components/angular/angular.min.js:67:421
    at http://localhost:9000/bower_components/angular-ui-router/release/angular-ui-router.min.js:7:15323 <div ui-view="" id="wrapper" class="ng-scope">

Code extracts:

```
angular.module('moneymojoApp', ['angularFileUpload'])


angular.module('moneymojoApp')
    .controller('OfxCtrl', [ '$scope', '$http', '$location', '$stateParams', '$cookieStore', '$upload',
        function ($scope, $http, $location, $stateParams, $cookieStore, $upload) {

   ....

file.upload = $upload
                .upload({
                    url: "https://xxxxxxxx.s3.amazonaws.com/",
                    method: 'POST',
                    data: {
                        key: $scope.key,
                        AWSAccessKeyId: "XXXXXXXXXXXXXXX",
                        acl: "private",
                        redirect: $scope.redirect,
                        policy: $scope.policy.policy,
                        signature: $scope.policy.signature,
                        "Content-Type": "text",
                        "Content-Length": "5000000",
                        "x-amz-meta-filetype": $scope.filetype,
                        bucket: "XXXXXXXXXXt"
                    },
                    file: file
                });

            file.upload.then(function (response) {
                $timeout(function () {
                    file.result = response.data;
                });
            }, function (response) {
                if (response.status > 0)
                    $scope.errorMsg = response.status + ': ' + response.data;
            });

            file.upload.progress(function (evt) {
                file.progress = Math.min(100, parseInt(100.0 * evt.loaded / evt.total));
            });

```

Any ideas what the problem is?

**Comment by timcullen** [comment]
Fixed it.  need to make sure script is called AND angularFileUpload is injected into app.  I was inadvertently doing one but not the other
